namespace Contoso.PromptOps.Application.PromptExecutions.Responses;

/// <summary>
/// Response model representing a completed prompt execution.
/// </summary>
/// <param name="Id">Unique prompt execution identifier.</param>
/// <param name="PromptTemplateId">Identifier of the prompt template that was executed.</param>
/// <param name="UserInput">User message sent to the AI provider.</param>
/// <param name="AiResponse">Response generated by the AI provider.</param>
/// <param name="DeploymentName">Azure OpenAI deployment used for execution.</param>
/// <param name="PromptTokens">Number of input tokens consumed, if available.</param>
/// <param name="CompletionTokens">Number of output tokens consumed, if available.</param>
/// <param name="TotalTokens">Total number of tokens consumed.</param>
/// <param name="DurationMs">Execution duration in milliseconds.</param>
/// <param name="CreatedAt">UTC timestamp when the execution was created.</param>
public sealed record PromptExecutionResponse(
    Guid Id,
    Guid PromptTemplateId,
    string UserInput,
    string AiResponse,
    string Model,
    int PromptTokens,
    int CompletionTokens,
    int TotalTokens,
    long DurationMs,
    DateTimeOffset CreatedAt);